### ISSUE TITLE
Migrate to new `SessionFactoryInterface` implementation

### ISSUE THREAD

**Issue by KorvinSzanto** [hissy/scaling-concrete5#1]
This is still compatible with the core, but session should likely be moved to the factory pattern rather than overriding the `Session` class.

See https://github.com/concrete5/concrete5/pull/3303

**Comment by hissy** [comment]
Is this migration is required to version 8? You have no plan to release more version 7.x?

**Comment by KorvinSzanto** [comment]
This is not required no, but it's going to be in the next v7.5 release so I
thought you want to use the modern version

**Comment by hissy** [comment]
Thanks for reply. This is not required because of backward compatibility, but I can use more modern way in next 7.5.x release. Correct?

**Comment by KorvinSzanto** [comment]
Correct. Except you could use it now without sacrificing support, want a pull request?

**Comment by hissy** [comment]
OK. I'll try it after the next version was released.

**Comment by KorvinSzanto** [comment]
No I was offering to make one

**Comment by hissy** [comment]
Hi @KorvinSzanto , could you review my referenced commit to fix this issue for me?

**Comment by hissy** [comment]
@KorvinSzanto Is this solution ok? thanks
